LARGEUR = 160
HAUTEUR = 120
FPS = 30
TITRE = "GALACTIX"

ETAT_MENU = 0
ETAT_JEU = 1
ETAT_PAUSE = 2
ETAT_GAME_OVER = 3
ETAT_VICTOIRE = 4

VITESSE_JOUEUR = 2
VITESSE_PROJECTILE_JOUEUR = 5
VITESSE_PROJECTILE_ENNEMI = 2

NB_ETOILES = 60
NB_VAGUES = 5

POINTS_BASIQUE = 100
POINTS_RAPIDE = 200
POINTS_LOURD = 350
POINTS_BOSS = 2000

TYPE_BASIQUE = 0
TYPE_RAPIDE = 1
TYPE_LOURD = 2
TYPE_BOSS = 3

COL_FOND = 0
COL_TEXTE = 7
COL_JOUEUR = 13
COL_MOTEUR = 9
COL_PROJ_JOUEUR = 11
COL_PROJ_ENNEMI = 8
COL_ENNEMI_BASIQUE = 8
COL_ENNEMI_RAPIDE = 9
COL_ENNEMI_LOURD = 2
COL_BOSS = 14
COL_EXPLOSION_1 = 10
COL_EXPLOSION_2 = 9
COL_EXPLOSION_3 = 8
COL_HUD = 1
COL_VAGUE = 10
COL_BARRE_VIE = 11
COL_BARRE_FOND = 5
